### PR TITLE
Implement Cmake build system for eyrie

### PR DESCRIPTION
**Pull request by grg-haas**
This PR implements a Cmake-based build system for the runtime, which hits some of the action items for Issue #42. Specifically, this PR accomplishes the following things:

1. Moved source files into separate directories, based on rough functionality
2. Similarly, restructured header files into their own subdirectories
3. Added a preprocessing pass to the `runtime.lds` file which allows us to use preprocessor macros in the linker script. This allows us to replace some magic values (`0x1000`, for example) with nice defines like `RISCV_PAGE_SIZE`.
4. Standardized compile options for plugins. Each plugin with name `NAME` now defines a compiler flag `USE_$NAME` to indicate that the option has been enabled.

Some things are left to do:

1. Determine if we still need the `.options_log` file -- I could not find any other references to the purpose of this file in the rest of Keystone. Is it safe to remove?
2. Also refactor the tests. These are not currently included in the cmake build system.
3. Any other edits requested by maintainers

### CODE REVIEW

**Comment by dkohlbre** [comment]
At least as designed, the .options_log was copied into a special section in the final ELF. This allowed us to check what options a given Eyrie was built with when we were working with multiple binaries. It is useful enough we should probably keep it.

**Comment by grg-haas** [comment]
Just pushed a commit which re-adds the options_log section back into the final executable. The case for the options has changed (lower -> upper), but this shouldn't really affect debugging

**Comment by grg-haas** [comment]
Rebased the branch on latest master to solve merge conflicts

**Comment by dayeol** [comment]
Could you push your stuffs into a new branch in keytone-enclave as a remote?
i.e., at the HEAD of your local branch,
```
git remote add upstream https://github.com/keystone-enclave/keystone-runtime
git push upstream grg-haas:feature/cmake-eyrie
```

And then re-create a PR to see if tests are triggered.
Thanks!

**Comment by dayeol** [comment]
@grg-haas The tests are failing!
The first one will need merging master (it will need this: https://github.com/keystone-enclave/keystone-runtime/commit/4580df4b12ec889e4628b03ed2598c6c6a723657)
The second one is `make format` which is missing in the new build system

**Pull request closed without merging**
